name: Test @airnode packages

on: push

jobs:
  build:
    name: Run Linting and Tests

    runs-on: ubuntu-latest

    steps:
    - name: Clone airnode
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Dependencies
      run: npm run bootstrap

    - name: Lint code
      run: npm run lint

    - name: Prepare config
      run: |
        cp packages/deployer/src/config-data/config.json.example packages/deployer/src/config-data/config.json

    - name: Build
      run: npm run build

    - name: Test adapter
      run: npm run test:adapter

    - name: Test protocol contracts
      run: npm run test:protocol

    - name: Test node
      run: npm run test:node

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        channel: '#technical'
        commit: true
        job_name: 'Airnode - Continuous Build'
        token: ${{ secrets.ACCESS_TOKEN }}
        type: ${{ job.status }}
        url: ${{ secrets.SLACK_WEBHOOK_URL }}

