name: Continuous Build

on: push

jobs:
  build:
    name: Run Linting and Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone airnode
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Dependencies
        run: yarn run bootstrap
      - name: Lint code
        run: yarn run lint
      - name: Prepare config
        run: |
          cp packages/deployer/src/config-data/config.json.example packages/deployer/src/config-data/config.json
      - name: Build
        run: yarn run build
      - uses: actions/cache@v2
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}

  test-adapter:
    name: Test @airnode/adapter
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn run test:adapter

  test-airnode-abi:
    name: Test @airnode/airnode-abi
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn run test:airnode-abi

  test-node:
    name: Test @airnode/node
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn run test:node

  test-protocol:
    name: Test @airnode/protocol
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn run test:protocol

  tests-pass:
    name: Tests passed
    runs-on: ubuntu-latest
    needs: [build, test-adapter, test-airnode-abi, test-node, test-protocol]
    steps:
      - run: exit 0

  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    needs: tests-pass
    steps:
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        channel: '#technical'
        commit: true
        job_name: 'Airnode - Continuous Build'
        token: ${{ secrets.ACCESS_TOKEN }}
        type: ${{ job.status }}
        url: ${{ secrets.SLACK_WEBHOOK_URL }}

